### ISSUE TITLE
Add market cap attribute to Stock()

### ISSUE THREAD

**Issue by camelCake** [moody-marlin/wmcm#2]
We should do this in a general way that can pull any data from Yahoo/Google. I've done this before in R. Trying to find out how.

**Comment by camelCake** [comment]
Yep. R's Quantmod::getQuote(what=yahooQF("Market Capitalization"))

**Comment by camelCake** [comment]
Investigate this: https://pypi.python.org/pypi/pystock-crawler

**Comment by moody-marlin** [comment]
Hey @camelCake for general notes / comments / things we "need to add", please use the wiki, don't raise an issue:
https://github.com/moody-marlin/wmcm/wikihttps://github.com/moody-marlin/wmcm/wiki

Issues should be reserved for code breaks / data breaks / testing new features.
